package com.axolotl.mcart.export;

import com.axolotl.mcart.core.PixelArtGenerator;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Litematica 投影文件（.litematic）导出器。
 *
 * 参考 Litematica / Litemapy 的 NBT 结构（格式版本 6）：
 * <pre>
 * Root
 * ├─ Version=6, SubVersion=1, MinecraftDataVersion
 * ├─ Metadata { Name, Author, Description, EnclosingSize{x,y,z},
 * │            RegionCount, TotalBlocks, TotalVolume,
 * │            TimeCreated, TimeModified, PreviewImageData }
 * └─ Regions
 *    └─ "Unnamed"
 *       ├─ Position{x,y,z} = {0,0,0}
 *       ├─ Size{x=width,y=height,z=length}
 *       ├─ BlockStatePalette: List&lt;Compound&gt; {Name[, Properties]}
 *       ├─ BlockStates: Long_Array，紧凑位打包（entry 可跨 long 边界）
 *       ├─ Entities / TileEntities / PendingBlockTicks / PendingFluidTicks: 空 List
 * </pre>
 * 位打包：bits = max(2, ceil(log2(paletteSize)))，索引顺序 index = y*W*L + z*W + x，
 * long 数组长度 = ceil(volume * bits / 64)，entry 连续排列、允许跨 long。
 */
public class LitematicExporter {

    /** Minecraft 1.20.1 数据版本，兼容性好 */
    private static final int MC_DATA_VERSION = 3465;
    private static final int FORMAT_VERSION = 6;
    private static final int SUB_VERSION = 1;

    public static void export(PixelArtGenerator.Result result, Path outputPath) throws IOException {
        int w = result.width;
        int h = result.height;
        int l = result.length;

        // 1. 构建方块状态调色板：air 固定为 0
        List<String> palette = new ArrayList<>();
        palette.add("minecraft:air");
        Map<String, Integer> stateIndex = new LinkedHashMap<>();
        stateIndex.put("minecraft:air", 0);
        for (var e : result.palette) {
            String state = e.baseColor.getBlockStateId(e.shade);
            if (!stateIndex.containsKey(state)) {
                stateIndex.put(state, palette.size());
                palette.add(state);
            }
        }
        int supportIdx = 0;
        boolean fixedSupport = h > 1 && !"#same".equals(result.supportBlockId);
        if (fixedSupport) {
            if (!stateIndex.containsKey(result.supportBlockId)) {
                stateIndex.put(result.supportBlockId, palette.size());
                palette.add(result.supportBlockId);
            }
            supportIdx = stateIndex.get(result.supportBlockId);
        }

        // 2. 紧凑位打包
        int nbits = Math.max(2, 32 - Integer.numberOfLeadingZeros(palette.size() - 1));
        int volume = w * h * l;
        int longCount = (int) Math.ceil((double) volume * nbits / 64.0);
        long[] bits = new long[longCount];
        long mask = (1L << nbits) - 1;

        int nonAir = 0;
        int index = 0;
        for (int y = 0; y < h; y++) {
            for (int z = 0; z < l; z++) {
                for (int x = 0; x < w; x++) {
                    int b = result.blockIds[y][z][x];
                    int state;
                    if (b == PixelArtGenerator.AIR) {
                        state = 0;
                    } else if (b == PixelArtGenerator.SUPPORT) {
                        String st = fixedSupport ? result.supportBlockId : SchemExporter.topState(result, x, z);
                        state = stateIndex.get(st);
                        nonAir++;
                    } else {
                        String st = result.palette.get(b).baseColor
                                .getBlockStateId(result.palette.get(b).shade);
                        state = stateIndex.get(st);
                        nonAir++;
                    }
                    writePacked(bits, index, state, nbits, mask);
                    index++;
                }
            }
        }

        // 3. 写 NBT
        NBTWriter nbt = new NBTWriter();
        nbt.writeRootCompound("");

        nbt.writeInt("Version", FORMAT_VERSION);
        nbt.writeInt("SubVersion", SUB_VERSION);
        nbt.writeInt("MinecraftDataVersion", MC_DATA_VERSION);

        long now = System.currentTimeMillis();

        // ---- Metadata ----
        nbt.beginCompound("Metadata");
        nbt.beginCompound("EnclosingSize");
        nbt.writeInt("x", w);
        nbt.writeInt("y", h);
        nbt.writeInt("z", l);
        nbt.endCompound();
        nbt.writeString("Author", "mc-pixel-art-converter");
        nbt.writeString("Description", "MC map art generated by mc-pixel-art-converter");
        nbt.writeString("Name", "Pixel Art");
        nbt.writeString("Software", "Jackin Lee software");
        nbt.writeInt("RegionCount", 1);
        nbt.writeLong("TimeCreated", now);
        nbt.writeLong("TimeModified", now);
        nbt.writeInt("TotalBlocks", nonAir);
        nbt.writeInt("TotalVolume", volume);
        nbt.writeIntArray("PreviewImageData", new int[0]);
        nbt.endCompound();

        // ---- Regions ----
        nbt.beginCompound("Regions");
        nbt.beginCompound("Unnamed");

        nbt.beginCompound("Position");
        nbt.writeInt("x", 0);
        nbt.writeInt("y", 0);
        nbt.writeInt("z", 0);
        nbt.endCompound();

        nbt.beginCompound("Size");
        nbt.writeInt("x", w);
        nbt.writeInt("y", h);
        nbt.writeInt("z", l);
        nbt.endCompound();

        // BlockStatePalette: List<Compound>
        nbt.beginList("BlockStatePalette", NBTWriter.TAG_Compound, palette.size());
        for (String state : palette) {
            nbt.beginListCompoundItem();
            nbt.writeString("Name", state);
            nbt.endCompound();
        }

        nbt.writeLongArray("BlockStates", bits);
        nbt.writeEmptyList("Entities", NBTWriter.TAG_Compound);
        nbt.writeEmptyList("TileEntities", NBTWriter.TAG_Compound);
        nbt.writeEmptyList("PendingBlockTicks", NBTWriter.TAG_Compound);
        nbt.writeEmptyList("PendingFluidTicks", NBTWriter.TAG_Compound);

        nbt.endCompound(); // Unnamed
        nbt.endCompound(); // Regions
        nbt.endCompound(); // Root

        Files.write(outputPath, nbt.toGzippedByteArray());
    }

    /** 把 value 写入紧凑 bit 流（允许跨 long 边界），与 LitematicaBitArray 一致 */
    private static void writePacked(long[] arr, int index, int value, int nbits, long mask) {
        int bitStart = index * nbits;
        int longIdx = bitStart >> 6;
        int bitOffset = bitStart & 0x3F;
        long v = value & mask;

        arr[longIdx] |= v << bitOffset;
        int overflow = bitOffset + nbits - 64;
        if (overflow > 0) {
            arr[longIdx + 1] |= v >>> (nbits - overflow);
        }
    }
}
